codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "35...100"

  status:
    project:
      default:
        target: 35%
        threshold: 2%
        if_not_found: success
        if_ci_failed: error

    patch:
      default:
        target: 40%
        threshold: 5%
        if_not_found: success

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "src/**/*.d.ts"
  - "src/pages/_app.tsx"
  - "src/pages/_document.tsx"
  - "src/assets/**"
  - "src/data/**"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "jest.config.ts"
  - "jest.setup.ts"
